"""Booster packs and their weights, taken from the game.

Generated by ops/gen_pack_data.py. Do not edit by hand.

`choose` is how many cards may be taken, `cards` how many are offered. The
order is the game's pool order and is load-bearing: the draw accumulates
weight along the list and takes the entry whose band contains the roll, so a
reordered list hands out different packs from the same seed.
"""

# (key, kind, weight, choose, cards, cost), in the game's pool order
PACK_DATA = [
    ('p_arcana_normal_1', 'Arcana', 1.0, 1, 3, 4),
    ('p_arcana_normal_2', 'Arcana', 1.0, 1, 3, 4),
    ('p_arcana_normal_3', 'Arcana', 1.0, 1, 3, 4),
    ('p_arcana_normal_4', 'Arcana', 1.0, 1, 3, 4),
    ('p_arcana_jumbo_1', 'Arcana', 1.0, 1, 5, 6),
    ('p_arcana_jumbo_2', 'Arcana', 1.0, 1, 5, 6),
    ('p_arcana_mega_1', 'Arcana', 0.25, 2, 5, 8),
    ('p_arcana_mega_2', 'Arcana', 0.25, 2, 5, 8),
    ('p_celestial_normal_1', 'Celestial', 1.0, 1, 3, 4),
    ('p_celestial_normal_2', 'Celestial', 1.0, 1, 3, 4),
    ('p_celestial_normal_3', 'Celestial', 1.0, 1, 3, 4),
    ('p_celestial_normal_4', 'Celestial', 1.0, 1, 3, 4),
    ('p_celestial_jumbo_1', 'Celestial', 1.0, 1, 5, 6),
    ('p_celestial_jumbo_2', 'Celestial', 1.0, 1, 5, 6),
    ('p_celestial_mega_1', 'Celestial', 0.25, 2, 5, 8),
    ('p_celestial_mega_2', 'Celestial', 0.25, 2, 5, 8),
    ('p_standard_normal_1', 'Standard', 1.0, 1, 3, 4),
    ('p_standard_normal_2', 'Standard', 1.0, 1, 3, 4),
    ('p_standard_normal_3', 'Standard', 1.0, 1, 3, 4),
    ('p_standard_normal_4', 'Standard', 1.0, 1, 3, 4),
    ('p_standard_jumbo_1', 'Standard', 1.0, 1, 5, 6),
    ('p_standard_jumbo_2', 'Standard', 1.0, 1, 5, 6),
    ('p_standard_mega_1', 'Standard', 0.25, 2, 5, 8),
    ('p_standard_mega_2', 'Standard', 0.25, 2, 5, 8),
    ('p_buffoon_normal_1', 'Buffoon', 0.6, 1, 2, 4),
    ('p_buffoon_normal_2', 'Buffoon', 0.6, 1, 2, 4),
    ('p_buffoon_jumbo_1', 'Buffoon', 0.6, 1, 4, 6),
    ('p_buffoon_mega_1', 'Buffoon', 0.15, 2, 4, 8),
    ('p_spectral_normal_1', 'Spectral', 0.3, 1, 2, 4),
    ('p_spectral_normal_2', 'Spectral', 0.3, 1, 2, 4),
    ('p_spectral_jumbo_1', 'Spectral', 0.3, 1, 4, 6),
    ('p_spectral_mega_1', 'Spectral', 0.07, 2, 4, 8),
]
