"""Vouchers and their pool order, taken from the game.

Generated by ops/gen_voucher_data.py. Do not edit by hand.

`requires` names the voucher that has to have been redeemed first -- every
upgrade is gated on its base. `extra` is the number the effect is written in
terms of, and it is the only thing separating most upgrades from their base:
Grabber and Nacho Tong are the same effect with a different `extra`.

The order is the game's pool order and is load-bearing: the draw picks an
index into it.
"""

# (key, name, cost, requires, extra), in the game's pool order
VOUCHER_DATA = [
    ('v_overstock_norm', 'Overstock', 10, '', 0),
    ('v_overstock_plus', 'Overstock Plus', 10, 'v_overstock_norm', 0),
    ('v_clearance_sale', 'Clearance Sale', 10, '', 25),
    ('v_liquidation', 'Liquidation', 10, 'v_clearance_sale', 50),
    ('v_hone', 'Hone', 10, '', 2),
    ('v_glow_up', 'Glow Up', 10, 'v_hone', 4),
    ('v_reroll_surplus', 'Reroll Surplus', 10, '', 2),
    ('v_reroll_glut', 'Reroll Glut', 10, 'v_reroll_surplus', 2),
    ('v_crystal_ball', 'Crystal Ball', 10, '', 3),
    ('v_omen_globe', 'Omen Globe', 10, 'v_crystal_ball', 4),
    ('v_telescope', 'Telescope', 10, '', 3),
    ('v_observatory', 'Observatory', 10, 'v_telescope', 1.5),
    ('v_grabber', 'Grabber', 10, '', 1),
    ('v_nacho_tong', 'Nacho Tong', 10, 'v_grabber', 1),
    ('v_wasteful', 'Wasteful', 10, '', 1),
    ('v_recyclomancy', 'Recyclomancy', 10, 'v_wasteful', 1),
    ('v_tarot_merchant', 'Tarot Merchant', 10, '', 2.4),
    ('v_tarot_tycoon', 'Tarot Tycoon', 10, 'v_tarot_merchant', 8),
    ('v_planet_merchant', 'Planet Merchant', 10, '', 2.4),
    ('v_planet_tycoon', 'Planet Tycoon', 10, 'v_planet_merchant', 8),
    ('v_seed_money', 'Seed Money', 10, '', 50),
    ('v_money_tree', 'Money Tree', 10, 'v_seed_money', 100),
    ('v_blank', 'Blank', 10, '', 5),
    ('v_antimatter', 'Antimatter', 10, 'v_blank', 15),
    ('v_magic_trick', 'Magic Trick', 10, '', 4),
    ('v_illusion', 'Illusion', 10, 'v_magic_trick', 4),
    ('v_hieroglyph', 'Hieroglyph', 10, '', 1),
    ('v_petroglyph', 'Petroglyph', 10, 'v_hieroglyph', 1),
    ('v_directors_cut', "Director's Cut", 10, '', 10),
    ('v_retcon', 'Retcon', 10, 'v_directors_cut', 10),
    ('v_paint_brush', 'Paint Brush', 10, '', 1),
    ('v_palette', 'Palette', 10, 'v_paint_brush', 1),
]
