"""Boss blinds and how the game picks one.

Generated by ops/gen_boss_data.py. Do not edit by hand.

`min` is the earliest ante a boss can appear at. `showdown` marks the finisher
bosses, which appear only on the ante that ends a run and never before ante 2.
`mult` is the blind's chip multiplier.

The order here is alphabetical by key on purpose: the game draws with
pseudorandom_element over a keyed table, which sorts the keys before picking,
so alphabetical order is part of the distribution.
"""

# key -> (name, min_ante, showdown, chip_mult)
BOSS_DATA = {
    'bl_arm': ('The Arm', 2, False, 2.0),
    'bl_club': ('The Club', 1, False, 2.0),
    'bl_eye': ('The Eye', 3, False, 2.0),
    'bl_final_acorn': ('Amber Acorn', 10, True, 2.0),
    'bl_final_bell': ('Cerulean Bell', 10, True, 2.0),
    'bl_final_heart': ('Crimson Heart', 10, True, 2.0),
    'bl_final_leaf': ('Verdant Leaf', 10, True, 2.0),
    'bl_final_vessel': ('Violet Vessel', 10, True, 6.0),
    'bl_fish': ('The Fish', 2, False, 2.0),
    'bl_flint': ('The Flint', 2, False, 2.0),
    'bl_goad': ('The Goad', 1, False, 2.0),
    'bl_head': ('The Head', 1, False, 2.0),
    'bl_hook': ('The Hook', 1, False, 2.0),
    'bl_house': ('The House', 2, False, 2.0),
    'bl_manacle': ('The Manacle', 1, False, 2.0),
    'bl_mark': ('The Mark', 2, False, 2.0),
    'bl_mouth': ('The Mouth', 2, False, 2.0),
    'bl_needle': ('The Needle', 2, False, 1.0),
    'bl_ox': ('The Ox', 6, False, 2.0),
    'bl_pillar': ('The Pillar', 1, False, 2.0),
    'bl_plant': ('The Plant', 4, False, 2.0),
    'bl_psychic': ('The Psychic', 1, False, 2.0),
    'bl_serpent': ('The Serpent', 5, False, 2.0),
    'bl_tooth': ('The Tooth', 3, False, 2.0),
    'bl_wall': ('The Wall', 2, False, 4.0),
    'bl_water': ('The Water', 2, False, 2.0),
    'bl_wheel': ('The Wheel', 2, False, 2.0),
    'bl_window': ('The Window', 1, False, 2.0),
}


def eligible_bosses(ante: int, used: dict, win_ante: int = 8) -> list:
    """Boss keys the game would consider for this ante, least-used only.

    Two filters, and the second is the one that is easy to miss. Showdown
    bosses appear only on the ante that ends a run; ordinary ones only when it
    does not. Then the set is narrowed to those used fewest so far, which is
    why a run does not see the same boss twice while others are unplayed --
    a uniform draw over all eligible bosses is a different game.
    """
    ante = max(1, ante)
    finisher = ante % win_ante == 0 and ante >= 2
    pool = []
    for key, (_name, min_ante, showdown, _mult) in BOSS_DATA.items():
        if showdown:
            if finisher:
                pool.append(key)
        elif min_ante <= ante and not finisher:
            pool.append(key)

    if not pool:
        return []
    fewest = min(used.get(key, 0) for key in pool)
    # Keys sorted, because pseudorandom_element sorts a keyed table before it
    # picks and the order therefore decides which key an index lands on.
    return sorted(key for key in pool if used.get(key, 0) == fewest)
