"""Consumable identity and shop pool order, taken from the game.

Generated by ops/gen_consumable_data.py. Do not edit by hand.

Two rules live in this data rather than in code:

  softlock   a Planet card for a hand nobody has played is not in the pool.
             Planet X, Ceres and Eris are the ones that matter, since Five of
             a Kind, Flush House and Flush Five need a deck built for them.
  excluded   Black Hole and The Soul never come from an ordinary draw.
"""

# set -> [(key, name, order, softlock, hand_type)], in the game's pool order
CONSUMABLE_DATA = {
    'Tarot': [
        ('c_fool', 'The Fool', 1, False, ''),
        ('c_magician', 'The Magician', 2, False, ''),
        ('c_high_priestess', 'The High Priestess', 3, False, ''),
        ('c_empress', 'The Empress', 4, False, ''),
        ('c_emperor', 'The Emperor', 5, False, ''),
        ('c_heirophant', 'The Hierophant', 6, False, ''),
        ('c_lovers', 'The Lovers', 7, False, ''),
        ('c_chariot', 'The Chariot', 8, False, ''),
        ('c_justice', 'Justice', 9, False, ''),
        ('c_hermit', 'The Hermit', 10, False, ''),
        ('c_wheel_of_fortune', 'The Wheel of Fortune', 11, False, ''),
        ('c_strength', 'Strength', 12, False, ''),
        ('c_hanged_man', 'The Hanged Man', 13, False, ''),
        ('c_death', 'Death', 14, False, ''),
        ('c_temperance', 'Temperance', 15, False, ''),
        ('c_devil', 'The Devil', 16, False, ''),
        ('c_tower', 'The Tower', 17, False, ''),
        ('c_star', 'The Star', 18, False, ''),
        ('c_moon', 'The Moon', 19, False, ''),
        ('c_sun', 'The Sun', 20, False, ''),
        ('c_judgement', 'Judgement', 21, False, ''),
        ('c_world', 'The World', 22, False, ''),
    ],
    'Planet': [
        ('c_mercury', 'Mercury', 1, False, 'Pair'),
        ('c_venus', 'Venus', 2, False, 'Three of a Kind'),
        ('c_earth', 'Earth', 3, False, 'Full House'),
        ('c_mars', 'Mars', 4, False, 'Four of a Kind'),
        ('c_jupiter', 'Jupiter', 5, False, 'Flush'),
        ('c_saturn', 'Saturn', 6, False, 'Straight'),
        ('c_uranus', 'Uranus', 7, False, 'Two Pair'),
        ('c_neptune', 'Neptune', 8, False, 'Straight Flush'),
        ('c_pluto', 'Pluto', 9, False, 'High Card'),
        ('c_planet_x', 'Planet X', 10, True, 'Five of a Kind'),
        ('c_ceres', 'Ceres', 11, True, 'Flush House'),
        ('c_eris', 'Eris', 12, True, 'Flush Five'),
    ],
    'Spectral': [
        ('c_familiar', 'Familiar', 1, False, ''),
        ('c_grim', 'Grim', 2, False, ''),
        ('c_incantation', 'Incantation', 3, False, ''),
        ('c_talisman', 'Talisman', 4, False, ''),
        ('c_aura', 'Aura', 5, False, ''),
        ('c_wraith', 'Wraith', 6, False, ''),
        ('c_sigil', 'Sigil', 7, False, ''),
        ('c_ouija', 'Ouija', 8, False, ''),
        ('c_ectoplasm', 'Ectoplasm', 9, False, ''),
        ('c_immolate', 'Immolate', 10, False, ''),
        ('c_ankh', 'Ankh', 11, False, ''),
        ('c_deja_vu', 'Deja Vu', 12, False, ''),
        ('c_hex', 'Hex', 13, False, ''),
        ('c_trance', 'Trance', 14, False, ''),
        ('c_medium', 'Medium', 15, False, ''),
        ('c_cryptid', 'Cryptid', 16, False, ''),
        ('c_soul', 'The Soul', 17, False, ''),
        ('c_black_hole', 'Black Hole', 18, False, ''),
    ],
}

# Never drawn from an ordinary pool; they have their own path.
EXCLUDED_FROM_POOLS = ('Black Hole', 'The Soul')
