"""Deck (back) effects, taken from the game.

Generated by ops/gen_deck_data.py. Do not edit by hand.

Each entry is the back's own config table. The names are the game's, so
`discards` means "extra discards each round" and `dollars` means "extra
starting money" -- a deck contributes these on top of the base rules rather
than replacing them.
"""

# display name -> (key, {config})
DECK_DATA = {
    'Abandoned Deck': ('b_abandoned', {'remove_faces': True}),
    'Anaglyph Deck': ('b_anaglyph', {'double_tag_after_boss': True}),
    'Black Deck': ('b_black', {'hands': -1, 'joker_slot': 1}),
    'Blue Deck': ('b_blue', {'hands': 1}),
    'Challenge Deck': ('b_challenge', {}),
    'Checkered Deck': ('b_checkered', {}),
    'Erratic Deck': ('b_erratic', {'randomize_rank_suit': True}),
    'Ghost Deck': ('b_ghost', {'spectral_rate': 2, 'consumables': ['c_hex']}),
    'Green Deck': ('b_green', {'extra_hand_bonus': 2, 'extra_discard_bonus': 1, 'no_interest': True}),
    'Magic Deck': ('b_magic', {'consumables': ['c_fool', 'c_fool'], 'voucher': 'v_crystal_ball'}),
    'Nebula Deck': ('b_nebula', {'consumable_slot': -1, 'voucher': 'v_telescope'}),
    'Painted Deck': ('b_painted', {'hand_size': 2, 'joker_slot': -1}),
    'Plasma Deck': ('b_plasma', {'ante_scaling': 2}),
    'Red Deck': ('b_red', {'discards': 1}),
    'Yellow Deck': ('b_yellow', {'dollars': 10}),
    'Zodiac Deck': ('b_zodiac', {'vouchers': ['v_tarot_merchant', 'v_planet_merchant', 'v_overstock_norm']}),
}
