"""Skip tags and their pool order, taken from the game.

Generated by ops/gen_tag_data.py. Do not edit by hand.

`min_ante` is the earliest ante a tag can be offered at, and `requires` names
a centre that has to have been discovered first. The order is the game's pool
order and is load-bearing: the draw picks an index into it.
"""

# (key, name, min_ante, requires), in the game's pool order
TAG_DATA = [
    ('tag_uncommon', 'Uncommon Tag', 0, ''),
    ('tag_rare', 'Rare Tag', 0, 'j_blueprint'),
    ('tag_negative', 'Negative Tag', 2, 'e_negative'),
    ('tag_foil', 'Foil Tag', 0, 'e_foil'),
    ('tag_holo', 'Holographic Tag', 0, 'e_holo'),
    ('tag_polychrome', 'Polychrome Tag', 0, 'e_polychrome'),
    ('tag_investment', 'Investment Tag', 0, ''),
    ('tag_voucher', 'Voucher Tag', 0, ''),
    ('tag_boss', 'Boss Tag', 0, ''),
    ('tag_standard', 'Standard Tag', 2, ''),
    ('tag_charm', 'Charm Tag', 0, ''),
    ('tag_meteor', 'Meteor Tag', 2, ''),
    ('tag_buffoon', 'Buffoon Tag', 2, ''),
    ('tag_handy', 'Handy Tag', 2, ''),
    ('tag_garbage', 'Garbage Tag', 2, ''),
    ('tag_ethereal', 'Ethereal Tag', 2, ''),
    ('tag_coupon', 'Coupon Tag', 0, ''),
    ('tag_double', 'Double Tag', 0, ''),
    ('tag_juggle', 'Juggle Tag', 0, ''),
    ('tag_d_six', 'D6 Tag', 0, ''),
    ('tag_top_up', 'Top-up Tag', 2, ''),
    ('tag_skip', 'Speed Tag', 0, ''),
    ('tag_orbital', 'Orbital Tag', 2, ''),
    ('tag_economy', 'Economy Tag', 0, ''),
]
