"""Generate src/jimbot_sim/joker_data.py from the real game centers.

The shop draws a joker by picking an index into a per-rarity pool, so the
order of those pools is part of the distribution and not a presentation
detail. Reading it out of the game beats typing it: 150 entries copied by hand
would be wrong somewhere, and wrong here means the shop offers the wrong
joker at the wrong rate without any rule looking incorrect.

    python ops/gen_joker_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from jimbot_sim.headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for r = 1, 4 do
    for i, v in ipairs(G.P_JOKER_RARITY_POOLS[r]) do
      local loc = G.localization.descriptions.Joker[v.key]
      t[#t+1] = table.concat({v.key, loc and loc.name or "?", r,
                              v.order or 0,
                              tostring(v.unlocked ~= false),
                              v.enhancement_gate or "",
                              v.no_pool_flag or "",
                              v.yes_pool_flag or ""}, "|")
    end
  end
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Joker identity and shop pool order, taken from the game.

The shop picks a joker by drawing an index into the pool for a rarity, so this
order is part of the distribution rather than a display detail: a pool in a
different order offers different jokers at different rates from the same seed,
while every rule still looks right.

Generated by ops/gen_joker_data.py against the real centers. Do not edit by
hand -- regenerate it.
"""

# name -> (key, rarity, order, unlocked, enhancement_gate, no_flag, yes_flag)
#
# The two flags gate a joker on the run's history rather than its deck. Gros
# Michel carries no_pool_flag "gros_michel_extinct" and leaves the pool once
# that is set; Cavendish carries yes_pool_flag for the same name and only
# enters afterwards. Neither is visible in the joker's text.
JOKER_DATA = {
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]
    assert len(rows) == 150, "expected 150 jokers, got %d" % len(rows)

    out = io.StringIO()
    out.write(HEADER)
    for (key, name, rarity, order, unlocked, gate,
         no_flag, yes_flag) in rows:
        out.write("    %r: (%r, %s, %s, %s, %r, %r, %r),\n"
                  % (name, key, rarity, order,
                     unlocked == "true", gate, no_flag,
                     yes_flag))
    out.write("}\n\n\n")
    out.write("def pool_for_rarity(rarity: int) -> list:\n")
    out.write('    """Joker keys of that rarity, in the game\'s pool order."""\n')
    out.write("    return [key for _, (key, r, _order, _u, _g, _n, _y)\n")
    out.write("            in sorted(JOKER_DATA.items(), key=lambda kv: kv[1][2])\n")
    out.write("            if r == rarity]\n")

    with open("src/jimbot_sim/joker_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())
    print("wrote src/jimbot_sim/joker_data.py with %d jokers" % len(rows))
    locked = [r[1] for r in rows if r[4] != "true"]
    print("locked by default: %d %s" % (len(locked), locked[:8]))


if __name__ == "__main__":
    main()
