"""Generate src/balatro/boss_data.py from the real game blinds.

Boss selection is not a uniform draw. The game keeps a usage count per boss,
narrows the eligible set to those used fewest, and only then rolls -- so a
simulator that picks uniformly offers the wrong boss at the wrong time even
with the generator reproduced exactly.

    python ops/gen_boss_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from balatro_headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for k, v in pairs(G.P_BLINDS) do
    if v.boss then
      t[#t+1] = table.concat({k, v.name, tostring(v.boss.min or 1),
                              tostring(v.boss.showdown and true or false),
                              tostring(v.mult or 2)}, "|")
    end
  end
  table.sort(t)
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Boss blinds and how the game picks one.

Generated by ops/gen_boss_data.py. Do not edit by hand.

`min` is the earliest ante a boss can appear at. `showdown` marks the finisher
bosses, which appear only on the ante that ends a run and never before ante 2.
`mult` is the blind's chip multiplier.

The order here is alphabetical by key on purpose: the game draws with
pseudorandom_element over a keyed table, which sorts the keys before picking,
so alphabetical order is part of the distribution.
"""

# key -> (name, min_ante, showdown, chip_mult)
BOSS_DATA = {
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]

    out = io.StringIO()
    out.write(HEADER)
    for key, name, min_ante, showdown, mult in sorted(rows):
        out.write("    %r: (%r, %s, %s, %s),\n"
                  % (key, name, int(float(min_ante)), showdown == "true",
                     float(mult)))
    out.write("}\n")

    with open("src/balatro/boss_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())

    ordinary = [r for r in rows if r[3] != "true"]
    finishers = [r for r in rows if r[3] == "true"]
    print("wrote %d bosses (%d ordinary, %d showdown)"
          % (len(rows), len(ordinary), len(finishers)))
    print("earliest antes:", sorted({int(float(r[2])) for r in ordinary}))


if __name__ == "__main__":
    main()
