"""Generate src/jimbot_sim/deck_data.py from the real game backs.

A deck is not decoration. Red Deck grants an extra discard every round, and a
simulator that ignores it hands the player one fewer -- which is the first
thing a whole-run comparison found, one step in.

    python ops/gen_deck_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from jimbot_sim.headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for k, v in pairs(G.P_CENTERS) do
    if v.set == "Back" then
      local cfg = {}
      for ck, cv in pairs(v.config or {}) do
        if type(cv) ~= "table" then
          cfg[#cfg+1] = ck .. "=" .. tostring(cv)
        else
          local inner = {}
          for _, iv in ipairs(cv) do inner[#inner+1] = tostring(iv) end
          cfg[#cfg+1] = ck .. "=[" .. table.concat(inner, ",") .. "]"
        end
      end
      t[#t+1] = table.concat({k, v.name, table.concat(cfg, " ")}, "|")
    end
  end
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Deck (back) effects, taken from the game.

Generated by ops/gen_deck_data.py. Do not edit by hand.

Each entry is the back's own config table. The names are the game's, so
`discards` means "extra discards each round" and `dollars` means "extra
starting money" -- a deck contributes these on top of the base rules rather
than replacing them.
"""

# display name -> (key, {config})
DECK_DATA = {
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]

    out = io.StringIO()
    out.write(HEADER)
    for key, name, config in sorted(rows, key=lambda r: r[1]):
        parsed = {}
        for item in config.split():
            field, _, value = item.partition("=")
            if value.startswith("["):
                parsed[field] = [v for v in value[1:-1].split(",") if v]
            else:
                try:
                    parsed[field] = int(float(value))
                except ValueError:
                    parsed[field] = (True if value == "true"
                                     else False if value == "false" else value)
        out.write("    %r: (%r, %r),\n" % (name, key, parsed))
    out.write("}\n")

    with open("src/jimbot_sim/deck_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())
    print("wrote %d decks" % len(rows))
    for key, name, config in sorted(rows, key=lambda r: r[1]):
        print("  %-18s %s" % (name, config or "(no config)"))


if __name__ == "__main__":
    main()
