"""Generate src/balatro/tag_data.py from the real game tags.

The simulator rolled skip rewards from eight tags of its own choosing with its
own generator, so a skipped blind handed over a tag the run never offered --
and an Uncommon or Rare tag hands over a joker, which is how a phantom Duo
turned up in a replay of somebody's actual game.

The game has twenty-four, drawn through the same pool machinery as jokers and
consumables, gated by a minimum ante and by whether what they require has been
discovered.

    python ops/gen_tag_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from balatro_headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for i, v in ipairs(G.P_CENTER_POOLS["Tag"]) do
    local loc = G.localization.descriptions.Tag[v.key]
    t[#t+1] = table.concat({v.key, loc and loc.name or "?",
                            tostring(v.min_ante or 0),
                            tostring(v.requires or ""),
                            tostring(v.order or 0)}, "|")
  end
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Skip tags and their pool order, taken from the game.

Generated by ops/gen_tag_data.py. Do not edit by hand.

`min_ante` is the earliest ante a tag can be offered at, and `requires` names
a centre that has to have been discovered first. The order is the game's pool
order and is load-bearing: the draw picks an index into it.
"""

# (key, name, min_ante, requires), in the game's pool order
TAG_DATA = [
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]

    out = io.StringIO()
    out.write(HEADER)
    for key, name, min_ante, requires, _order in rows:
        out.write("    (%r, %r, %s, %r),\n"
                  % (key, name, int(float(min_ante)), requires))
    out.write("]\n")

    with open("src/balatro/tag_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())
    print("wrote %d tags" % len(rows))
    gated = [(r[1], r[2]) for r in rows if float(r[2]) > 1]
    print("gated by ante:", gated)


if __name__ == "__main__":
    main()
