"""Generate src/jimbot_sim/voucher_data.py from the real game vouchers.

The simulator had eleven vouchers written from memory, with names that are
not the game's and effects invented to match. The game has thirty-two: sixteen
base and sixteen upgrades, each upgrade gated on having redeemed its base.

A voucher is bought once and lasts the run, so a wrong one is not a wrong
roll -- it is a wrong run from then on. And they are drawn through the same
pool machinery as everything else, so an invented list also puts every later
voucher draw in the wrong place.

    python ops/gen_voucher_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from jimbot_sim.headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for i, v in ipairs(G.P_CENTER_POOLS["Voucher"]) do
    local loc = G.localization.descriptions.Voucher[v.key]
    local req = ""
    if v.requires then
      for _, r in ipairs(v.requires) do
        req = (req == "" and r) or (req .. "," .. r)
      end
    end
    t[#t+1] = table.concat({v.key, loc and loc.name or "?",
                            tostring(v.cost or 10), req,
                            tostring((v.config and v.config.extra) or 0)}, "|")
  end
  return table.concat(t, " ;; ") end)()"""

HEADER = '''"""Vouchers and their pool order, taken from the game.

Generated by ops/gen_voucher_data.py. Do not edit by hand.

`requires` names the voucher that has to have been redeemed first -- every
upgrade is gated on its base. `extra` is the number the effect is written in
terms of, and it is the only thing separating most upgrades from their base:
Grabber and Nacho Tong are the same effect with a different `extra`.

The order is the game's pool order and is load-bearing: the draw picks an
index into it.
"""

# (key, name, cost, requires, extra), in the game's pool order
VOUCHER_DATA = [
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split(" ;; ")
            if line.strip()]

    out = io.StringIO()
    out.write(HEADER)
    for key, name, cost, requires, extra in rows:
        value = float(extra)
        out.write("    (%r, %r, %d, %r, %r),\n"
                  % (key, name, int(float(cost)), requires,
                     int(value) if value == int(value) else value))
    out.write("]\n")

    with open("src/jimbot_sim/voucher_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())
    print("wrote %d vouchers (%d upgrades)"
          % (len(rows), sum(1 for r in rows if r[3])))


if __name__ == "__main__":
    main()
