"""Generate src/balatro/consumable_data.py from the real game centers.

Consumable pools work like the joker pools -- ordered lists drawn by index --
with two rules of their own. Planet cards carry a softlock: Planet X, Ceres and
Eris only enter the pool once the hand they level has actually been played, so
a run that never makes a Five of a Kind is never offered the card for it. And
Black Hole and The Soul are excluded from ordinary draws entirely; they arrive
only through their own special path.

    python ops/gen_consumable_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from balatro_headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for _, set in ipairs({"Tarot", "Planet", "Spectral"}) do
    for i, v in ipairs(G.P_CENTER_POOLS[set]) do
      local loc = G.localization.descriptions[set][v.key]
      t[#t+1] = table.concat({
        set, v.key, loc and loc.name or "?", v.order or 0,
        tostring((v.config and v.config.softlock) and true or false),
        (v.config and v.config.hand_type) or ""}, "|")
    end
  end
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Consumable identity and shop pool order, taken from the game.

Generated by ops/gen_consumable_data.py. Do not edit by hand.

Two rules live in this data rather than in code:

  softlock   a Planet card for a hand nobody has played is not in the pool.
             Planet X, Ceres and Eris are the ones that matter, since Five of
             a Kind, Flush House and Flush Five need a deck built for them.
  excluded   Black Hole and The Soul never come from an ordinary draw.
"""

# set -> [(key, name, order, softlock, hand_type)], in the game's pool order
CONSUMABLE_DATA = {
'''

EXCLUDED = ("Black Hole", "The Soul")


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]

    by_set = {}
    for card_set, key, name, order, softlock, hand_type in rows:
        by_set.setdefault(card_set, []).append(
            (key, name, int(float(order)), softlock == "true", hand_type))

    out = io.StringIO()
    out.write(HEADER)
    for card_set in ("Tarot", "Planet", "Spectral"):
        out.write("    %r: [\n" % card_set)
        for entry in by_set.get(card_set, []):
            out.write("        %r,\n" % (entry,))
        out.write("    ],\n")
    out.write("}\n\n")
    out.write("# Never drawn from an ordinary pool; they have their own path.\n")
    out.write("EXCLUDED_FROM_POOLS = %r\n" % (EXCLUDED,))

    with open("src/balatro/consumable_data.py", "w", encoding="utf-8") as fh:
        fh.write(out.getvalue())

    for card_set, entries in sorted(by_set.items()):
        locked = [e[1] for e in entries if e[3]]
        print("%-9s %2d cards, softlocked: %s"
              % (card_set, len(entries), locked or "none"))


if __name__ == "__main__":
    main()
