"""Generate src/jimbot_sim/pack_data.py from the real booster pool.

Packs are weighted, and the weights are not uniform across sizes: a mega pack
is a quarter as likely as a normal one, and Spectral packs are rarer again.
The pool order matters too, because the draw walks it accumulating weight and
takes the entry whose band contains the roll.

    python ops/gen_pack_data.py
"""

import io
import sys

sys.path.insert(0, "src")

from jimbot_sim.headless.runtime import HeadlessBalatro     # noqa: E402

QUERY = """(function()
  local t = {}
  for i, v in ipairs(G.P_CENTER_POOLS["Booster"]) do
    t[#t+1] = table.concat({
      v.key, tostring(v.kind), tostring(v.weight or 1),
      tostring(v.config and v.config.choose or 1),
      tostring(v.config and v.config.extra or 0),
      tostring(v.cost or 4)}, "|")
  end
  return table.concat(t, "\\n") end)()"""

HEADER = '''"""Booster packs and their weights, taken from the game.

Generated by ops/gen_pack_data.py. Do not edit by hand.

`choose` is how many cards may be taken, `cards` how many are offered. The
order is the game's pool order and is load-bearing: the draw accumulates
weight along the list and takes the entry whose band contains the roll, so a
reordered list hands out different packs from the same seed.
"""

# (key, kind, weight, choose, cards, cost), in the game's pool order
PACK_DATA = [
'''


def main() -> None:
    engine = HeadlessBalatro().boot()
    rows = [line.split("|") for line in engine.eval(QUERY).split("\n")
            if line.strip()]

    out = io.StringIO()
    out.write(HEADER)
    for key, kind, weight, choose, cards, cost in rows:
        out.write("    (%r, %r, %s, %s, %s, %s),\n"
                  % (key, kind, float(weight), int(float(choose)),
                     int(float(cards)), int(float(cost))))
    out.write("]\n")

    with open("src/jimbot_sim/pack_data.py", "w", encoding="utf-8") as handle:
        handle.write(out.getvalue())

    kinds = {}
    for _key, kind, weight, *_rest in rows:
        kinds[kind] = kinds.get(kind, 0) + float(weight)
    total = sum(kinds.values())
    print("wrote %d packs" % len(rows))
    for kind, weight in sorted(kinds.items(), key=lambda kv: -kv[1]):
        print("  %-10s weight %5.2f  %5.1f%%" % (kind, weight,
                                                 100 * weight / total))


if __name__ == "__main__":
    main()
